config/routes.rb
Rails.application.routes.draw do
  
 # Root alternatives: root "main#index"                  root to: "main#index"                get "", to: "main#index"                 get "/", to: "main#index"
  root "main#index"

  #Rout for user actions
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get"sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  #Rout para página about
  get "/about", to: "about#index"

  # Routes that already were in here from step one
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest



  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email adress"}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  #before other methods (sessions, regristration...) are processed this will be processed
  before_action :set_current_user 

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id:session[:user_id]) #find_by serve pra nao crashar a pagina caso o usuário do cookie não seja encontrado -- a alternativa, find sem o by, da erro se o user no cookie não for encontrado
    end
  end

  def require_user_logged_in!
    if Current.user.nil?
      redirect_to sign_in_path, alert: "You must be signed in to do that." 
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      #send email
      PasswordMailer.with(user: @user).reset.deliver_now #could be "later" pra não demorar
    end
    
    redirect_to root_path, notice: "If an account with that email was found, we  have sent email a link to reset your password"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end  

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please log in"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end



end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!
  
  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'User created successfully!'
    else
      # Se o save falhar, renderiza a view `new` com o status `unprocessable_entity`
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Certifique-se de que este método está definido corretamente
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to root_path, notice: "Logged in successfuly"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if session[:user_id]
      session[:user_id] = nil
      redirect_to root_path, notice: "Logged out"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="d-flex align-items center justify-content-center">
  <H1> Well... I agree with the main page ^^ </H1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "First App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    
    <!-- Esse aqui de baixo é o layout do bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- esses aqui de baixo são os layouts padrão do código base -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <!-- "Execute" o código parcial na pasta shared no arquivo _navbar.html.erb (...) -->
    <%= render partial: "shared/navbar" %>
    <%= render partial: "shared/flash"%>

  <!-- Container cria uma área central que evita que o conteúdo do texto fique colado nas margens -->
    <div class="container">
      <%= yield %>
    </div>
    <!-- Esse aqui de baixo é o layout do bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items center justify-content-center vh100">
  <H1 class="mb-4"> Welcome to my first functional project! </H1>
</div>

<div class="d-flex align-items center justify-content-center">
  <H2 class="text-muted"> <br> Here you can find: <br>  <br>
  - functional user authetication; <br>
  - registrations; <br> 
  - password management/recovery by email. </H2>
</div>

app/views/password_resets/edit.html.erb
<h1> Reset your password </h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

  <!-- form.object only works if "model" is defined above --> 

  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do | message |%>
      <div> <%= message %> </div>
    <% end %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="mb-3">
  <%= form.submit "Reset Password", class: "btn btn-primary"%>
  </div>

<% end %>

app/views/password_resets/new.html.erb
<h1> Forgot your password? </h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "example@mail.com" %>
  </div>

  <div class="mb-3">
  <%= form.submit "Reset Password", class: "btn btn-primary"%>
  </div>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

<div class="alert alert-info mt-4" role="alert">
  <%= flash[:notice]%>
</div>
<%end%>


<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
  <%= flash[:alert]%>
</div>

<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <!-- Esse era o código em html, em baixo está a alternativa que, caso mude o nome da URL pra outra coisa, exemplo "About Us", o código não precisa mudar -->
    <!-- link_to "ruby code helper", URL "é o href", class  -->
    <!-- tinha antes: <a class="navbar-brand" href="#">Navbar</a> --> 
    <%= link_to "1st App", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <!-- tinha antes: <a class="nav-link active" aria-current="page" href="/">Home</a> -->
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <!-- tinha antes: <a class="nav-link" href="/about">About</a> --> 
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>

          <!-- Navbar do lado direito daqui pra baixo --> 
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>